### ISSUE TITLE
Possible paid collaboration for a project?

### ISSUE THREAD

**Issue by SocialKitLtd** [joaopfg/Non-local-patch-based-image-inpainting-algorithm#1]
Hey there, I didn't find an email in your profile so I'm writing it here.

Would you be interested in a paid collaboration with my company? We are looking to develop an app that removes objects from images (similar to this: https://apps.apple.com/us/app/touchretouch/id373311252) using inpaint technique. We will take care of the entire app development, including the actual component for the masking, etc'. The user will use his fingers to choose the "removed object". But we need help to develop to object inpaint removal algorithm under the hood.  
Is it something you'll find interesting?

Roi

**Comment by joaopfg** [comment]
Hello,

Yes, I'm really interested in it. I coded this project about inpaint
removal algorithm for a college project and at that time I didn't have much
time to explore it. So I would appreciate this opportunity to go deeper
into the papers about image inpainting and implement a better algorithm. I
don't know much about app development but I would like to go deeper into it
too. Could you give me more info about this project, please?

Thanks in advance,

João

**Comment by joaopfg** [comment]
Hello,

I'm master student at École Polytechnique in France, currently doing research internship at CNRS.
I'm really interested in your proposal. I coded this project about inpaint removal algorithm for a college project and I would appreciate this opportunity to go deeper into the papers about image inpainting and implement a better algorithm. There are a lot of things to explore about it. I also would like to go deeper into mobile development. Could you give me more info about this project, please?

You can send email to jfontesgoncalves@gmail.com.

Thanks in advance,

João

**Comment by SocialKitLtd** [comment]
Sent you an email :)

BR,
Roi
